variables: !include /home/xzcappon/phd/datasets/flavour_tagging/weighting_studies/variables.yaml
global_cuts: !include splits/simple-split.yaml

# for k-folded splits, only required for final trainings of GN2
# global_cuts: !include splits/fold0.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.nekumari.601589.e8549_s4162_r14622_p6057.tdd.EMPFlow_kfold.24_2_37.24-02-15_Dump_run3_feb24_output.h5/*.h5"

zprime: &zprime
  name: zprime
  equal_jets: False
  pattern:
    - "user.nekumari.800030.e8514_s4162_r14622_p6057.tdd.EMPFlow_kfold.24_2_37.24-02-15_Dump_run3_feb24_output.h5/*.h5"


lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt_btagJes, ">", 20_000]
    - [pt_btagJes, "<", 250_000]
highpt: &highpt
  name: highpt
  cuts:
    - [pt_btagJes, ">", 250_000]
    - [pt_btagJes, "<", 6_000_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [bjets, cjets, ujets]
    num_jets: 6_000_000
    equal_jets: False

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [taujets]
    num_jets: 2_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [bjets, cjets, ujets]
    num_jets: 3_000_000
    equal_jets: False

  - region:
      <<: *highpt
    sample:
      <<: *zprime
    flavours: [taujets]
    num_jets: 1_000_000
    equal_jets: False


resampling:
  target: cjets
  method: none
  sampling_fraction: auto
  variables:
    pt_btagJes:
      bins: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
    absEta_btagJes:
      bins: [[0, 2.5, 20]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: jets
  batch_size: 1_000_000
  num_jets_estimate: 25_000_000
  base_dir: /home/xzcappon/phd/datasets/flavour_tagging/weighting_studies/noresample_v2
  ntuple_dir: /home/xzcappon/central_dumps/p6057/gn2v01/full/

reweighting:
  reweights:
    - group: jets
      reweight_vars: [pt_btagJes, absEta_btagJes]
      bins: 
        pt_btagJes: [[20_000, 250_000, 50], [250_000, 1_000_000, 50], [1_000_000, 6_000_000, 50]]
        absEta_btagJes: [[0, 2.5, 20]]
      class_var: flavour_label
      class_target: mean

